# Generated by Django 3.1.4 on 2021-02-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('impressao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impressao.tipoimpressao'),
        ),
    ]
