# Generated by Django 3.1.4 on 2021-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cliente',
            field=models.BooleanField(blank=True, null=True, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcionario',
            field=models.BooleanField(blank=True, null=True, verbose_name='funcionario'),
        ),
    ]
