# Generated by Django 3.1.4 on 2021-02-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=55, null=True, verbose_name='comentario')),
                ('uri_arquivo', models.FileField(upload_to='')),
                ('qtd_copias', models.SmallIntegerField(verbose_name='qtd_copias')),
                ('visualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='visualizado_em')),
                ('prazo_entrega', models.DateTimeField(blank=True, null=True, verbose_name='prazo_entrega')),
            ],
        ),
        migrations.CreateModel(
            name='TipoImpressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='descricao')),
            ],
        ),
    ]
