# Generated by Django 3.1.4 on 2021-02-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0002_auto_20210202_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressao',
            name='colorida',
            field=models.BooleanField(default=False, verbose_name='colorida'),
        ),
    ]
