# Generated by Django 3.1.4 on 2021-02-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0003_impressao_colorida'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressao',
            name='imprimida',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_imprimida'),
        ),
    ]
