# Generated by Django 3.1.4 on 2021-02-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0004_impressao_imprimida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comentario'),
        ),
    ]
