# Generated by Django 3.1.4 on 2021-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0006_auto_20210207_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='uri_arquivo',
            field=models.FileField(max_length=400, upload_to=''),
        ),
    ]
