# Generated by Django 3.1.4 on 2021-02-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0008_auto_20210213_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
        migrations.AddField(
            model_name='impressao',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impressao.destinacao'),
        ),
    ]
