# Generated by Django 3.1.4 on 2021-02-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0009_auto_20210213_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinacao',
            new_name='Turma',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='destino',
        ),
        migrations.AddField(
            model_name='impressao',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impressao.turma'),
        ),
    ]
