# Generated by Django 3.1.4 on 2021-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressao', '0011_auto_20210213_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='qtd_laudas_imprimidas',
            field=models.IntegerField(blank=True, default=0, verbose_name='qtd_laudas_imprimidas'),
        ),
    ]
